---
permalink: upgrade/task_upgrade_snapcenter.html 
sidebar: sidebar 
keywords: upgrade, upgrade snapcenter server, windows 
summary: È possibile utilizzare il file eseguibile del programma di installazione del server SnapCenter per aggiornare il server SnapCenter. 
---
= Aggiornare il server SnapCenter sull'host Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario aggiornare SnapCenter Server per accedere alle funzionalità e ai miglioramenti più recenti forniti nella versione più recente.

.Prima di iniziare
* L'host del server SnapCenter deve essere aggiornato con gli aggiornamenti di Windows, senza riavvii del sistema in sospeso.
* Prima di avviare l'aggiornamento, assicurarsi che non siano in esecuzione altre operazioni.
* Eseguire il backup del database del repository SnapCenter (MySQL) dopo essersi assicurati che non vi siano processi in esecuzione.  Si consiglia di effettuare questa operazione prima di aggiornare SnapCenter Server e il plug-in di Exchange.
+
Per informazioni, vedere link:../admin/concept_manage_the_snapcenter_server_repository.html#back-up-the-snapcenter-repository["Eseguire il backup del repository SnapCenter"^].

* Eseguire il backup di tutti i file di configurazione SnapCenter modificati sull'host del server SnapCenter o sull'host del plug-in.


Esempi di file di configurazione di SnapCenter: SnapDriveService.exe.config, SMCoreServiceHost.exe.config e così via.

* Se hai installato più versioni del plug-in personalizzato in SnapCenter 5.0, prima di eseguire l'aggiornamento alla versione 6.0 o successiva, dovresti eseguire i cmdlet di PowerShell per rimuovere tutte le versioni precedenti del plug-in personalizzato (tranne quella più recente) dal repository SnapCenter (database NSM).
+
** Correre `Open-SmConnection` e accedi utilizzando le credenziali del ruolo SnapCenterAdmin
** Correre `Remove-SmPluginPackage -PluginName M<plug-in name> -PluginVersion <version number>`
+
Per ulteriori informazioni, consulta  https://kb.netapp.com/data-mgmt/SnapCenter/SC_KBs/SnapCenter_6.0_upgrade_fails_in_nsm_repository_upgrade_SQL_script_8["L'aggiornamento a SnapCenter 6.0 o versione successiva non riesce"] .





.A proposito di questa attività
* Durante l'aggiornamento, SnapCenter esegue uno script SQL per aggiornare i dati di Exchange nel database NSM, convertendo il DAG e il nome abbreviato dell'host in FQDN.  Ciò si applica solo se si utilizza SnapCenter Server con il plug-in Exchange.
* Se hai messo manualmente l'host del server in modalità di manutenzione, dopo l'aggiornamento seleziona *Host* > *Attiva pianificazione* per far uscire l'host del server dalla modalità di manutenzione.
* Per il plug-in SnapCenter per Microsoft SQL Server, il plug-in SnapCenter per Microsoft Exchange Server e il plug-in SnapCenter per Microsoft Windows, si consiglia di aggiornare sia il server che gli host dei plug-in alla versione 4.7 affinché IL PERCORSO SCRIPT venga eseguito.
+
Per le pianificazioni di backup e verifica esistenti con prescritture e postscript attivati nel criterio, le operazioni di backup continueranno a funzionare dopo l'aggiornamento.

+
Nella pagina *Dettagli lavoro*, un messaggio di avviso consiglia al cliente di copiare gli script nel PERCORSO_SCRIPT e modificare il criterio per fornire un percorso relativo al PERCORSO_SCRIPT. Per il lavoro del ciclo di vita clone, il messaggio di avviso viene visualizzato a livello di lavoro secondario.



.Fasi
. Scaricare il pacchetto di installazione del server SnapCenter dal sito del supporto NetApp.
+
https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab[]

. Creare una copia del file web.config che si trova in C: File di programma NetApp SnapCenter WebApp.
. Esportare le pianificazioni host del plug-in SnapCenter dall'Utilità di pianificazione di Windows per ripristinarle se l'aggiornamento non riesce.
+
`md d:\\SCBackup``schtasks /query /xml /TN taskname >> "D:\SCBackup\taskname.xml"`

. Creare il dump del database MySQL SnapCenter se il backup del repository non è configurato.
+
`md d:\\SCBackup``mysqldump --all-databases --single-transaction --add-drop-database --triggers --routines --events -u root -p > D:\SCBackup\SCRepoBackup.dmp`

+
Quando richiesto, inserire la password.

. Fare doppio clic sul file .exe scaricato per avviare l'aggiornamento di SnapCenter Server.
+
Dopo aver avviato l'aggiornamento, SnapCenter esegue dei controlli preliminari.  Se il sistema non soddisfa i requisiti minimi, SnapCenter mostra messaggi di errore o di avviso.  Correggi eventuali errori prima di continuare.  Puoi ignorare gli avvisi e procedere.

+

NOTE: SnapCenter continuerà a utilizzare la password esistente del database del repository MySQL Server fornita durante l'installazione della versione precedente del server SnapCenter.

. Seleziona *Aggiorna*.
+
Se in qualsiasi momento selezioni *Annulla*, SnapCenter interrompe l'aggiornamento.  Il server SnapCenter non torna allo stato precedente.

+
*Procedura consigliata:* disconnettersi e riconnettersi oppure aprire un nuovo browser per accedere all'interfaccia utente SnapCenter .



.Al termine
* Se il plug-in viene installato usando un utente sudo, copiare le sha224 chiavi disponibili in _C:\ProgramData\NetApp\SnapCenter\Package Repository\sc_unix_plugins_checksum.txt_ per aggiornare il file _/etc/sudoers_.
* È necessario eseguire una nuova ricerca delle risorse sull'host del server.
+
Se SnapCenter visualizza lo stato dell'host del server come arrestato, attendere qualche istante ed eseguire una nuova individuazione.  È anche possibile modificare il valore del parametro *HostRefreshInterval* (il valore predefinito è 3600 secondi) impostandolo su un valore superiore a 10 minuti.

* Se l'aggiornamento non riesce, pulire l'installazione non riuscita, reinstallare la versione precedente SnapCenter e ripristinare il database NSM allo stato precedente.
* Dopo aver aggiornato l'host del server, è necessario aggiornare anche i plug-in prima di aggiungere qualsiasi sistema di storage.

